devel::m4: bump to v1.4.21
As for binutils compilation of the previous version was broken on
archlinux:

 stdlib.h:827:20 error: expected identifier or '(' before '_Generic'