devel::binutils: bump to v2.46.0
Compiling 2.45.1 on archlinux (gcc 15/glibc 2.43) fails with:

 stdlib.h:827:20 error: expected identifier or '(' before '_Generic'

Update to 2.46.0 solves this.