Revert "devel::dune: bump to v3.21.0"
Build fails with:

/.../_boot/otherlibs/stdune/src/copyfile_stubs.c:126: undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking (exit code 1)
make: *** [Makefile:43: _boot/dune.exe] Error 2

This reverts commit 52c3ebf1e221149c862d4c9e218ba70185905d49.